# This file was generated by GoReleaser. DO NOT EDIT.
cask "dazio" do
  postflight_steps do
    run "{{HOMEBREW_PREFIX}}/bin/dazio", args: ["service", "restart"], print_stdout: true
  end

  version "0.1.19"

  on_macos do
    on_arm do
      sha256 "56ef31dd9ceddf7667f3d811317167789c2a37a3c6374dc725defd8543a4604c"
      url "https://github.com/boostsecurityio/dazio/releases/download/v#{version}/dazio_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "702da42bb1456ffb225fa17b95ec41119be3838943c8b4a605f206382b3e55e1"
      url "https://github.com/boostsecurityio/dazio/releases/download/v#{version}/dazio_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "65998ff20fc7b7d2069ebcf5dae0203d1f65e3ddacbd87bc137e99dae598d56c"
      url "https://github.com/boostsecurityio/dazio/releases/download/v#{version}/dazio_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "320a05629b2088fc132648e94516ff3895cb5aa216559d1b615c24a884fe15bd"
      url "https://github.com/boostsecurityio/dazio/releases/download/v#{version}/dazio_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dazio"
  desc "Developer-workstation supply-chain scanner"
  homepage "https://github.com/boostsecurityio/dazio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dazio"

  generate_completions_from_executable "dazio", "completion"

  # No zap stanza required
end
