# This file was generated by GoReleaser. DO NOT EDIT.
cask "dazio" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "35a08cf3953437675111cafc7a74091c05c7fe90cfe72b23517b49cd1df99472"
      url "https://github.com/boostsecurityio/dazio/releases/download/v#{version}/dazio_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2aad3076e857a76cbb995582dadb7cbcd4a250a6e35b10ea92f54d6afae8c8e6"
      url "https://github.com/boostsecurityio/dazio/releases/download/v#{version}/dazio_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "49166a1a1a6585e68cf594ff6b2dc605f030c589b7723201c9f7dd7daf0fb088"
      url "https://github.com/boostsecurityio/dazio/releases/download/v#{version}/dazio_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "17f376a2da6caf096e3a195c8a479699a101769ddec791a7edee21e0ef3d5bc2"
      url "https://github.com/boostsecurityio/dazio/releases/download/v#{version}/dazio_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dazio"
  desc "Developer-workstation supply-chain scanner"
  homepage "https://github.com/boostsecurityio/dazio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dazio"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dazio"]
    end
  end

  generate_completions_from_executable "dazio", "completion"

  # No zap stanza required
end
