# This file was generated by GoReleaser. DO NOT EDIT.
cask "dazio" do
  postflight_steps do
    run "{{HOMEBREW_PREFIX}}/bin/dazio", args: ["service", "restart"], print_stdout: true
  end

  version "0.1.14"

  on_macos do
    on_arm do
      sha256 "12bae4798ec186861151242b9e1d6ec3f8ec9aea6e702ec00b986978a320da64"
      url "https://github.com/boostsecurityio/dazio/releases/download/v#{version}/dazio_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3bae53cc43089cc819c86780fb1c129e55d88430924643747d5f81ef248f975d"
      url "https://github.com/boostsecurityio/dazio/releases/download/v#{version}/dazio_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fca5e6ed1d6205d5ad47fb689937edb2daa59c001dec42a41a71d44f9ba72873"
      url "https://github.com/boostsecurityio/dazio/releases/download/v#{version}/dazio_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "437217f2a6a601d06d4de8c68311cf24ef1a805b56c03f37bcf19273d94abe11"
      url "https://github.com/boostsecurityio/dazio/releases/download/v#{version}/dazio_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dazio"
  desc "Developer-workstation supply-chain scanner"
  homepage "https://github.com/boostsecurityio/dazio"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dazio"

  generate_completions_from_executable "dazio", "completion"

  # No zap stanza required
end
